using Volo.Abp;

namespace AgriculturalRecordRenewal.EntityFrameworkCore;

public abstract class AgriculturalRecordRenewalEntityFrameworkCoreTestBase : AgriculturalRecordRenewalTestBase<AgriculturalRecordRenewalEntityFrameworkCoreTestModule>
{

}
