using AgriculturalRecordRenewal.EntityFrameworkCore;
using Xunit;

namespace AgriculturalRecordRenewal.EntityFrameworkCore;

public class AgriculturalRecordRenewalEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AgriculturalRecordRenewalEntityFrameworkCoreFixture>
{

}
